[{application, rebar3_codecov, Config}] = CONFIG,

{Apps0, Config0} = case lists:keytake(applications, 1, Config) of
                       false ->
                           {[], CONFIG};
                       {value, {applications, A}, Cfg} ->
                           {A, Cfg}
                   end,

Apps = case list_to_integer(erlang:system_info(otp_release)) of
           N when N >= 27 ->
               Apps0;
           _ ->
               [jsone, rfc3339 | Apps0]
       end,

[{application, rebar3_codecov, [{applications, Apps} | Config]}].
